name: check PR to main

on:
  pull_request:
    branches:
    - main
jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm ci
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm run test